config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: [:new, :create, :index] do
      member do
        get :make_default
      end
    end
  end

  root to: "projects#index"

  resources :projects, only: [:index, :show, :edit, :update]  do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true

  has_many :tickets, dependent: :delete_all
  has_many :roles, dependent: :delete_all

  def has_member?(user)
    roles.exists?(user_id: user)
  end

  [:manager, :editor, :viewer].each do |role|
    define_method "has_#{role}?" do |user|
      roles.exists?(user_id: user, role: role)
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created"
      redirect_to @project
    else
      flash.now[:error] = "Project has not been created"
      render :new
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted"
    redirect_to projects_path
  end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found"
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]

  def index
    @projects = policy_scope(Project)
  end

  def show
    authorize @project, :show?
    @tickets = @project.tickets
  end

  def edit
    authorize(@project, :update?)
  end

  def update
    authorize(@project, :update?)
    if @project.update(project_params)
      flash[:notice] = "Project has been updated"
      redirect_to @project
    else
      flash.now[:alert] = "Project has not been updated"
      render :edit
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found"
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>
<%= render "form" %>

app/views/projects/index.html.erb
<% content_for :actions do %>
  <% admins_only do %>
    <%= link_to "New Project", new_admin_project_path, class: "button action" %>
  <% end %>
<% end %>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project %>
    </li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<header class="project">
  <h1><%= @project.name %></h1>
</header>

<% content_for :actions do %>
  <ul>
    <li>
      <% if policy(@project).update? %>
        <%= link_to "Edit Project", edit_project_path(@project), class: "button action" %>
      <% end %>
    </li>

    <li>
      <% if policy(Ticket.new(project: @project)).create? %>
        <%= link_to "New Ticket", new_project_ticket_path(@project), class: "button safe" %>
      <% end %>
    </li>

    <li>
      <% admins_only do %>
        <%= link_to "Delete Project",
          admin_project_path(@project),
          method: :delete,
          data: { confirm: "Are you sure you want to delete this project" },
          class: "button danger" %>
      <% end %>
    </li>
  </ul>
<% end %>

<div class="project-body">
  <%= form_tag search_project_tickets_path(@project), method: :get, class: "search-bar" do %>
    <%= text_field_tag "search", params[:search], type: "search" %>
    <%= submit_tag "Search" %>
  <% end %>
  <hr>

  <p><%= @project.description %></p>

  <div id="tickets">
    <ul>
      <% @tickets.each do |ticket| %>
        <li>
          <%= link_to ticket.name, [@project, ticket] %>
        </li>
      <% end %>
    </ul>
  </div>
</div>