config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: "application#index"

    resources :projects, only: [:new, :create, :destroy]
    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: [:new, :create, :index] do
      member do
        get :make_default
      end
    end
  end

  root to: "projects#index"

  resources :projects, only: [:index, :show, :edit, :update]  do
    resources :tickets do
      collection do
        get :search
      end
      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :attachments, only: [:show, :new]

end

app/models/state.rb
class State < ApplicationRecord
  def to_s
    name
  end

  def make_default!
    State.update_all(default: false)
    update!(default: true)
  end

  def self.default
    find_by(default: true)
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::ApplicationController

  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)

    if @state.save
      flash[:notice] = "State has been created"
      redirect_to admin_states_path
    else
      flash.now[:error] = "State has now been created"
      render :new
    end
  end

  def make_default
    @state = State.find(params[:id])
    @state.make_default!
    flash[:notice] = "'#{@state.name}' is the new default state"
    redirect_to admin_states_path
  end

  private
  def state_params
    params.require(:state).permit(:name, :colour)
  end
end

app/views/admin/states/_form.html.erb
<%= simple_form_for [:admin, state] do |f| %>
  <%= f.input :name %>
  <%= f.input :colour %>
  <%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<% content_for :actions do %>
  <ul>
    <li>
      <%= link_to "New State", new_admin_state_path, class: "button safe" %>
    </li>
  </ul>
<% end %>

<ul id="states">
  <% @states.each do |state| %>
    <li>
      <%= render "states/state", state: state %>
      <% if state.default? %>
        (Default)
      <% else %>
        <%= link_to "Make Default", make_default_admin_state_path(state) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/states/new.html.erb
<h2>New State</h2>
<%= render 'form', state: @state %>

app/views/admin/states/state.html.erb
<h4><%= state.name %></h4>